### ISSUE TITLE
Option to leave standard for Kevlar & Helmet

### ISSUE THREAD

**Issue by crashzk** [shanapu/Hosties---Remove-Armor-on-LR#1]
Firstly thanks for sharing the plugin, I found it very useful on my servers.

But using it some players gave some suggestions, would be these.

Instead of completely removing the Kevlar & Helmet it would be nice if you have the option to leave a pattern, for example, they will stick with Kevlar & Helmet instead of completely removing it.)

Another suggestion would be to also include life, that is, reduce the life of the players that are in the LR to 100.

Because the option of life, some servers use the SM: RPG, it's the upgrade option to increase Life, Kevlar & Helmet, so I think it would be nice that option too.

**Comment by shanapu** [comment]
hi,
I added the suggest feature with convars and new cfg file. Take a look at the readme file.

Thanks for your request!
